# obeze

#preload = /home/zycata/Pictures/Wallpapers/chiaki.png

#wallpaper = , /home/zycata/Pictures/Wallpapers/chiaki.png
splash = false
wallpaper {
  monitor = 
  path = /home/zycata/Pictures/Wallpapers/chiaki.png
  fit_mode = cover
}
