input {
    kb_layout = us
    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35

    focus_on_close = 1
    sensitivity = 0 # nso change for touchad
    touchpad {
        
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }

}
device {
    name = compx-2.4g-wireless-receiver
    sensitivity = -1
}
binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
}

